<?xml version="1.0"?>
<!--
adapter_macro(prefix)

Adapter between arm and gripper for Paris setup.
-->
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="adapter" params="prefix parent *origin">
    <xacro:property name="adapter_radius" value="0.040" />
    <xacro:property name="adapter_length" value="0.030" />
    <xacro:property name="adapter_weight" value="0.100" />

    <joint name="${prefix}adapter_fix" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${prefix}adapter_link"/>
    </joint>

    <link name="${prefix}adapter_link">
      <visual>
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${adapter_radius}" length="${adapter_length}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${adapter_radius}" length="${adapter_length}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.06 -0.025 0.06" rpy="0 1.57 0" />
        <geometry>
          <cylinder radius="0.01" length="0.05"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.06 0.025 0.06" rpy="0 1.57 0" />
        <geometry>
          <cylinder radius="0.01" length="0.05"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${adapter_radius}" length="${adapter_length}" mass="${adapter_weight}">
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}adapter_toolside_fix" type="fixed">
      <origin xyz="0 0 ${adapter_length}" rpy="0 0 0"/>
      <parent link="${prefix}adapter_link"/>
      <child link="${prefix}adapter_toolside"/>
    </joint>
    <link name="${prefix}adapter_toolside" />
  </xacro:macro>
</robot>
