<?xml version="1.0"?>
<!--
adapter_macro(prefix)

Adapter between arm and gripper for Paris setup.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="grenoble_adapter" params="prefix">

    <xacro:property name="adapter_radius" value="0.040" />
    <xacro:property name="adapter_length" value="0.084" />
    <xacro:property name="adapter_weight" value="0.100" />
    
    <joint name="${prefix}tool0-adapter_fixed_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${prefix}tool0"/>
      <child link="${prefix}adapter_link"/>
    </joint>

    <link name="${prefix}adapter_link">
      <visual>
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${adapter_radius}" length="${adapter_length}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${adapter_radius}" length="${adapter_length}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${adapter_radius}" length="${adapter_length}" mass="${adapter_weight}">
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <!--joint name="${prefix}adapter-palm_fixed_joint" type="fixed">
      <origin xyz="0 0 ${adapter_length+0.045}" rpy="${pi/2} 0 ${3*pi/4}"/>
      <parent link="${prefix}adapter_link"/>
      <child link="${prefix}hand_palm"/>
    </joint-->

    <!-- hand base -->
    <link name="${prefix}hand_base" />

    <joint name="${prefix}adapter-hand_base_fixed_joint" type="fixed">
      <origin xyz="0 0 ${adapter_length}" rpy="0 0 ${3*pi/4}"/>
      <parent link="${prefix}adapter_link"/>
      <child link="${prefix}hand_base"/>
    </joint>

    <!-- hand palm -->
    <joint name="${prefix}hand_base-palm_fixed_joint" type="fixed">
      <origin xyz="0 0 ${0.045}" rpy="${pi/2} 0 0"/>
      <parent link="${prefix}hand_base"/>
      <child link="${prefix}hand_palm"/>
    </joint> 


  </xacro:macro>

</robot>
