<?xml version="1.0"?>
<!--
adapter_macro(prefix)

Adapter between arm and gripper for Grenoble setup.
-->
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="paris_adapter" params="prefix parent *origin">

    <xacro:property name="adapter_radius" value="0.040" />
    <xacro:property name="adapter_length" value="0.030" />
    <xacro:property name="adapter_weight" value="0.100" />

    <xacro:property name="tube_length" value="0.100" />
    <xacro:property name="tube_radius" value="0.022" />
    <xacro:property name="tube_remove" value="0.080" />

    <joint name="${prefix}tool0-adapter_fixed_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${prefix}adapter_link"/>
    </joint>

    <link name="${prefix}adapter_link">
      <visual>
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${adapter_radius}" length="${adapter_length}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${adapter_radius}" length="${adapter_length}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.06 -0.025 0.06" rpy="0 1.57 0" />
        <geometry>
          <cylinder radius="0.01" length="0.05"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.06 0.025 0.06" rpy="0 1.57 0" />
        <geometry>
          <cylinder radius="0.01" length="0.05"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="${tube_remove} 0.0 ${-tube_length/2.0 + 0.02}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${tube_radius}" length="${tube_length}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${adapter_radius}" length="${adapter_length}" mass="${adapter_weight}">
        <origin xyz="0.0 0.0 ${adapter_length/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <!-- hand base -->
    <link name="${prefix}hand_base" />

    <joint name="${prefix}adapter-hand_base_fixed_joint" type="fixed">
      <origin xyz="0 0 ${adapter_length}" rpy="0 0 0"/>
      <parent link="${prefix}adapter_link"/>
      <child link="${prefix}hand_base"/>
    </joint>

    <!-- hand palm -->
    <joint name="${prefix}hand_base-palm_fixed_joint" type="fixed">
      <origin xyz="0 0 ${0.045}" rpy="${pi/2} 0 0"/>
      <parent link="${prefix}hand_base"/>
      <child link="${prefix}hand_palm"/>
    </joint>

    <!-- vive tracker mount -->
    <link name="${prefix}tool_mount"/>
    <link name="${prefix}tool_tracker"/>

    <joint name="${prefix}tool0-tool_mount-fixed_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 ${-pi*5/12}"/> <!-- 115-180 grad -->
      <parent link="${prefix}tool0"/>
      <child link="${prefix}tool_mount"/>
    </joint>

    <joint name="${prefix}tool_mount-tool_tracker-fixed_joint" type="fixed">
      <origin xyz="0 -0.120 0.004" rpy="0 0 0"/>
      <parent link="${prefix}tool_mount"/>
      <child link="${prefix}tool_tracker"/>
    </joint>

  </xacro:macro>

</robot>
