controller_list:
  - name: fake_manipulator_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - hand_palm_finger_1_joint
      - hand_finger_1_joint_1
      - hand_finger_1_joint_2
      - hand_finger_1_joint_3
      - hand_palm_finger_2_joint
      - hand_finger_2_joint_1
      - hand_finger_2_joint_2
      - hand_finger_2_joint_3
      - hand_finger_middle_joint_1
      - hand_finger_middle_joint_2
      - hand_finger_middle_joint_3