## joint_state_controller
hand_joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

## gripper action controller (for standart control)
hand_gripper_controller:
   type: position_controllers/GripperActionController
   joint: hand_finger_middle_joint_1
   action_monitor_rate: 20
   goal_tolerance: 0.01
   max_effort: 100
   stall_velocity_threshold: 0.001
   stall_timeout: 0.1

## joint trajectory controller (for individual finger control)
hand_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
   - hand_finger_1_joint_1
   - hand_finger_2_joint_1
   - hand_finger_middle_joint_1
   - hand_palm_finger_1_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01
      hand_finger_1_joint_1: {trajectory: 0.01, goal: 0.01}
      hand_finger_2_joint_1: {trajectory: 0.01, goal: 0.01}
      hand_finger_middle_joint_1: {trajectory: 0.01, goal: 0.01}
      hand_palm_finger_1_joint: {trajectory: 0.01, goal: 0.01}
   stop_trajectory_duration: 0.2
   state_publish_rate:  10
   action_monitor_rate: 30
   allow_partial_joints_goal: True