## joint_state_controller
$(arg prefix)joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

## gripper action controller (for standart control)
$(arg prefix)gripper_controller:
   type: position_controllers/GripperActionController
   joint: $(arg prefix)finger_middle_joint_1

## joint trajectory controller (for individual finger control)
$(arg prefix)trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
   - $(arg prefix)finger_1_joint_1
   - $(arg prefix)finger_2_joint_1
   - $(arg prefix)finger_middle_joint_1sss
   - $(arg prefix)palm_finger_1_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      $(arg prefix)finger_1_joint_1: {trajectory: 0.01, goal: 0.01}
      $(arg prefix)finger_2_joint_1: {trajectory: 0.01, goal: 0.01}
      $(arg prefix)finger_middle_joint_1: {trajectory: 0.01, goal: 0.01}
      $(arg prefix)palm_finger_1_joint: {trajectory: 0.01, goal: 0.01}
   stop_trajectory_duration: 0.2
   state_publish_rate:  10
   action_monitor_rate: 30